### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by RetroKoH** [dannye/pokered-gbc#10]
Before I get into this... let me say, I'm trying to port the changes into a fresh pokered disasm. I seem to have almost everything accounted for but I'm getting an odd error:

error: Trying to go to a previous address (0x0010 to 0x0008)

Have you ever seen this when putting this together?

**Comment by dannye** [comment]
Sounds like the rst sections are stepping on each other. Take a look at the top of home.asm

**Comment by dannye** [comment]
Can I ask why you are reapplying these changes to a clean pokered repo? This repo was last synced with pokered on April 13th

**Comment by RetroKoH** [comment]
I figured it out. I needed to comment out a few lines of the link file. And to answer your question, I'm trying to reapply it so as to try and better understand how it all works.

**Comment by rawr51919** [comment]
This really isn't an issue with pokered-gbc itself, but with applying the GBC stuff on top of regular RBY. Can this be closed?

**Comment by RetroKoH** [comment]
Ah, apologies. Yes. Sorry about that. I wasn't sure how best to post such a
question. I appreciate your feedback!

**Comment by dannye** [comment]
No worries. I don't mind you using the issues for questions about this project

**Comment by RetroKoH** [comment]
Can I PM you if I have modding questions unrelated to the project? I've got a mod I'm trying to do and I've hit a snag
