### ISSUE TITLE
Bug: Player sprite disappears while using itemfinder

### ISSUE THREAD

**Issue by melthelesbian** [dannye/pokered-gbc#20]
In the crysaudio branch, if you use the itemfinder and it successfully finds an item, the player's sprite disappears while the audio plays until the text box is printed for the results.

**Comment by dannye** [comment]
Confirmed this bug happens on the master branch as well; not related to crysaudio.

**Comment by dannye** [comment]
Fixed via 1103424c7e329a79448f158d5b7e6ce8009be3e9.
